spring.application.name=UT4Springboot_Lucas

spring.datasource.url=jdbc:mysql://localhost:3306/Juegos?createDatabaseIfNotExist=true

spring.datasource.username=root

spring.datasource.password=Huanito@33

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
